CREATE TABLE `users` (
  `username` varchar(50) NOT NULL,
  `password` varchar(50) default 'NOT_USED',
  `description` varchar(50) default NULL,
  `enabled` tinyint(4) NOT NULL default '1',
  PRIMARY KEY  (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

insert into `users` values
 ('admin','admin',null,'1'),
 ('user','user',null,'1');

CREATE TABLE `groups` (
  `id` int(11) NOT NULL auto_increment,
  `group_name` varchar(50) NOT NULL,
  `description` varchar(50) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `group_name_indx` (`group_name`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

insert into `groups` values('1','openreg-dev','Openregistry developers');

CREATE TABLE `group_authorities` (
  `id` int(11) NOT NULL auto_increment,
  `group_id` int(11) NOT NULL,
  `authority` varchar(50) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `fk_group_authorities_group` (`group_id`),
  CONSTRAINT `fk_group_authorities_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

insert into `group_authorities` values
 ('1','1','ROLE_ADMIN'),
 ('2','1','ROLE_USER'),
 ('3','1','ROLE');

CREATE TABLE `group_members` (
  `id` int(11) NOT NULL auto_increment,
  `username` varchar(50) NOT NULL,
  `group_id` int(11) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `fk_group_members_group` (`group_id`),
  KEY `fk_group_members_users` (`username`),
  CONSTRAINT `fk_group_members_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`),
  CONSTRAINT `fk_group_members_users` FOREIGN KEY (`username`) REFERENCES `users` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

insert into `group_members` values
 ('1','admin','1'),
 ('2','user','1');

DROP table key_sequence;
create table key_sequence (sequence_value BIGINT not null) type=MYISAM;
insert into key_sequence values(0);

insert into `ctd_countries` values
 ('1','US','United States'),
 ('2','AF','Afghanistan'),
 ('3','AL','Albania'),
 ('4','DZ','Algeria'),
 ('5','AS','American Samoa'),
 ('6','AD','Andorra'),
 ('7','AO','Angola'),
 ('8','AI','Anguilla'),
 ('9','AQ','Antarctica'),
 ('10','AG','Antigua and Barbuda'),
 ('11','AR','Argentina'),
 ('12','AM','Armenia'),
 ('13','AW','Aruba'),
 ('14','AU','Australia'),
 ('15','AT','Austria'),
 ('16','AZ','Azerbaijan'),
 ('17','BS','Bahamas'),
 ('18','BH','Bahrain'),
 ('19','BD','Bangladesh'),
 ('20','BB','Barbados'),
 ('21','BY','Belarus'),
 ('22','BE','Belgium'),
 ('23','BZ','Belize'),
 ('24','BJ','Benin'),
 ('25','BM','Bermuda'),
 ('26','BT','Bhutan'),
 ('27','BO','Bolivia'),
 ('28','BA','Bosnia and Herzegovina'),
 ('29','BW','Botswana'),
 ('30','BV','Bouvet Island'),
 ('31','BR','Brazil'),
 ('32','IO','British Indian Ocean Territory'),
 ('33','VG','British Virgin Islands'),
 ('34','BN','Brunei Darussalam'),
 ('35','BG','Bulgaria'),
 ('36','BF','Burkina Faso'),
 ('37','BI','Burundi'),
 ('38','KH','Cambodia'),
 ('39','CM','Cameroon'),
 ('40','CA','Canada'),
 ('41','CV','Cape Verde'),
 ('42','KY','Cayman Islands'),
 ('43','CF','Central African Republic'),
 ('44','TD','Chad'),
 ('45','CL','Chile'),
 ('46','CN','China'),
 ('47','CX','Christmas Island'),
 ('48','CC','Cocos (keeling) Islands'),
 ('49','CO','Colombia'),
 ('50','KM','Comoros'),
 ('51','CG','Congo'),
 ('52','CK','Cook Islands'),
 ('53','CR','Costa Rica'),
 ('54','CI','Cote d\'Ivoire'),
 ('55','HR','Croatia'),
 ('56','CU','Cuba'),
 ('57','CY','Cyprus'),
 ('58','CZ','Czech Republic'),
 ('59','KP','Democratic People\'s Republic of Korea'),
 ('60','CD','Democratic Republic of the Congo'),
 ('61','DK','Denmark'),
 ('62','DJ','Djibouti'),
 ('63','DM','Dominica'),
 ('64','DO','Dominican Republic'),
 ('65','TP','East Timor'),
 ('66','EC','Ecuador'),
 ('67','EG','Egypt'),
 ('68','SV','El Salvador'),
 ('69','GQ','Equatorial Guinea'),
 ('70','ER','Eritrea'),
 ('71','EE','Estonia'),
 ('72','ET','Ethiopia'),
 ('73','FO','Faeroe Islands'),
 ('74','FK','Falkland Islands (Malvinas)'),
 ('75','FM','Micronesia, Federated States of'),
 ('76','FJ','Fiji'),
 ('77','FI','Finland'),
 ('78','MK','The former Yugoslav Republic of Macedonia'),
 ('79','FR','France'),
 ('80','GF','French Guiana'),
 ('81','PF','French Polynesia'),
 ('82','TF','French Southern Territories'),
 ('83','GA','Gabon'),
 ('84','GM','Gambia'),
 ('85','GE','Georgia'),
 ('86','DE','Germany'),
 ('87','GH','Ghana'),
 ('88','GI','Gibraltar'),
 ('89','GR','Greece'),
 ('90','GL','Greenland'),
 ('91','GD','Grenada'),
 ('92','GP','Guadeloupe'),
 ('93','GU','Guam'),
 ('94','GT','Guatemala'),
 ('95','GN','Guinea'),
 ('96','GW','Guinea-Bissau'),
 ('97','GY','Guyana'),
 ('98','HT','Haiti'),
 ('99','HM','Heard Island And Mcdonald Islands'),
 ('100','VA','Holy See'),
 ('101','HN','Honduras'),
 ('102','HK','Hong Kong Special Administrative Region of China'),
 ('103','HU','Hungary'),
 ('104','IS','Iceland'),
 ('105','IN','India'),
 ('106','ID','Indonesia'),
 ('107','IR','Iran (Islamic Republic of)'),
 ('108','IQ','Iraq'),
 ('109','IE','Ireland'),
 ('110','IL','Israel'),
 ('111','IT','Italy'),
 ('112','JM','Jamaica'),
 ('113','JP','Japan'),
 ('114','JO','Jordan'),
 ('115','KZ','Kazakhstan'),
 ('116','KE','Kenya'),
 ('117','KI','Kiribati'),
 ('118','KW','Kuwait'),
 ('119','KG','Kyrgyzstan'),
 ('120','LA','Lao People\'s Democratic Republic'),
 ('121','LV','Latvia'),
 ('122','LB','Lebanon'),
 ('123','LS','Lesotho'),
 ('124','LR','Liberia'),
 ('125','LY','Libyan Arab Jamahiriya'),
 ('126','LI','Liechtenstein'),
 ('127','LT','Lithuania'),
 ('128','LU','Luxembourg'),
 ('129','MO','Macau'),
 ('130','MG','Madagascar'),
 ('131','MW','Malawi'),
 ('132','MY','Malaysia'),
 ('133','MV','Maldives'),
 ('134','ML','Mali'),
 ('135','MT','Malta'),
 ('136','MH','Marshall Islands'),
 ('137','MQ','Martinique'),
 ('138','MR','Mauritania'),
 ('139','MU','Mauritius'),
 ('140','YT','Mayotte'),
 ('141','MX','Mexico'),
 ('142','MC','Monaco'),
 ('143','MN','Mongolia'),
 ('144','MS','Montserrat'),
 ('145','MA','Morocco'),
 ('146','MZ','Mozambique'),
 ('147','MM','Myanmar'),
 ('148','NA','Namibia'),
 ('149','NR','Nauru'),
 ('150','NP','Nepal'),
 ('151','NL','Netherlands'),
 ('152','AN','Netherlands Antilles'),
 ('153','NC','New Caledonia'),
 ('154','NZ','New Zealand'),
 ('155','NI','Nicaragua'),
 ('156','NE','Niger'),
 ('157','NG','Nigeria'),
 ('158','NU','Niue'),
 ('159','NF','Norfolk Island'),
 ('160','MP','Northern Mariana Islands'),
 ('161','NO','Norway'),
 ('162','OM','Oman'),
 ('163','PK','Pakistan'),
 ('164','PW','Palau'),
 ('165','PA','Panama'),
 ('166','PG','Papua New Guinea'),
 ('167','PY','Paraguay'),
 ('168','PE','Peru'),
 ('169','PH','Philippines'),
 ('170','PN','Pitcairn'),
 ('171','PL','Poland'),
 ('172','PT','Portugal'),
 ('173','PR','Puerto Rico'),
 ('174','QA','Qatar'),
 ('175','KR','Republic of Korea'),
 ('176','MD','Republic of Moldova'),
 ('177','RO','Romania'),
 ('178','RE','Reunion'),
 ('179','RU','Russian Federation'),
 ('180','RW','Rwanda'),
 ('181','SH','Saint Helena'),
 ('182','KN','Saint Kitts and Nevis'),
 ('183','LC','Saint Lucia'),
 ('184','PM','Saint Pierre and Miquelon'),
 ('185','VC','Saint Vincent and the Grenadines'),
 ('186','WS','Samoa'),
 ('187','SM','San Marino'),
 ('188','ST','Sao Tome and Principe'),
 ('189','SA','Saudi Arabia'),
 ('190','SN','Senegal'),
 ('191','SC','Seychelles'),
 ('192','SL','Sierra Leone'),
 ('193','SG','Singapore'),
 ('194','SK','Slovakia'),
 ('195','SI','Slovenia'),
 ('196','SB','Solomon Islands'),
 ('197','SO','Somalia'),
 ('198','ZA','South Africa'),
 ('199','GS','South Georgia And The South Sandwich Islands'),
 ('200','ES','Spain'),
 ('201','LK','Sri Lanka'),
 ('202','SD','Sudan'),
 ('203','SR','Suriname'),
 ('204','SJ','Svalbard and Jan Mayen Islands'),
 ('205','SZ','Swaziland'),
 ('206','SE','Sweden'),
 ('207','CH','Switzerland'),
 ('208','SY','Syrian Arab Republic'),
 ('209','TW','Taiwan Province of China'),
 ('210','TJ','Tajikistan'),
 ('211','TH','Thailand'),
 ('212','TG','Togo'),
 ('213','TK','Tokelau'),
 ('214','TO','Tonga'),
 ('215','TT','Trinidad and Tobago'),
 ('216','TN','Tunisia'),
 ('217','TR','Turkey'),
 ('218','TM','Turkmenistan'),
 ('219','TC','Turks and Caicos Islands'),
 ('220','TV','Tuvalu'),
 ('221','UG','Uganda'),
 ('222','UA','Ukraine'),
 ('223','AE','United Arab Emirates'),
 ('224','GB','United Kingdom'),
 ('225','TZ','United Republic of Tanzania'),
 ('226','UM','United States Minor Outlying Islands'),
 ('227','VI','United States Virgin Islands'),
 ('228','UY','Uruguay'),
 ('229','UZ','Uzbekistan'),
 ('230','VU','Vanuatu'),
 ('231','VE','Venezuela'),
 ('232','VN','Viet Nam'),
 ('233','WF','Wallis and Futuna Islands'),
 ('234','EH','Western Sahara'),
 ('235','YE','Yemen'),
 ('236','YU','Yugoslavia'),
 ('237','ZM','Zambia'),
 ('238','ZW','Zimbabwe');


insert into `ctd_regions` values('1','AK','Alaska','1'),
 ('2','AL','Alabama','1'),
 ('3','AR','Arkansas','1'),
 ('4','AS','American Samoa','1'),
 ('5','AZ','Arizona','1'),
 ('6','CA','California','1'),
 ('7','CO','Colorado','1'),
 ('8','CT','Connecticut','1'),
 ('9','DC','District of Columbia','1'),
 ('10','DE','Delaware','1'),
 ('11','FL','Florida','1'),
 ('12','FM','Federated States of Micronesia','1'),
 ('13','GA','Georgia','1'),
 ('14','GU','Guam','1'),
 ('15','HI','Hawaii','1'),
 ('16','IA','Iowa','1'),
 ('17','ID','Idaho','1'),
 ('18','IL','Illinois','1'),
 ('19','IN','Indiana','1'),
 ('20','KS','Kansas','1'),
 ('21','KY','Kentucky','1'),
 ('22','LA','Louisiana','1'),
 ('23','MA','Massachusetts','1'),
 ('24','MD','Maryland','1'),
 ('25','ME','Maine','1'),
 ('26','MH','Marshall Islands','1'),
 ('27','MI','Michigan','1'),
 ('28','MN','Minnesota','1'),
 ('29','MO','Missouri','1'),
 ('30','MP','Northern Mariana Islands','1'),
 ('31','MS','Mississippi','1'),
 ('32','MT','Montana','1'),
 ('33','NC','North Carolina','1'),
 ('34','ND','North Dakota','1'),
 ('35','NE','Nebraska','1'),
 ('36','NH','New Hampshire','1'),
 ('37','NJ','New Jersey','1'),
 ('38','NM','New Mexico','1'),
 ('39','NV','Nevada','1'),
 ('40','NY','New York','1'),
 ('41','OH','Ohio','1'),
 ('42','OK','Oklahoma','1'),
 ('43','OR','Oregon','1'),
 ('44','PA','Pennsylvania','1'),
 ('45','PR','Puerto Rico','1'),
 ('46','PW','Palau','1'),
 ('47','RI','Rhode Island','1'),
 ('48','SC','South Carolina','1'),
 ('49','SD','South Dakota','1'),
 ('50','TN','Tennessee','1'),
 ('51','TX','Texas','1'),
 ('52','UT','Utah','1'),
 ('53','VA','Virginia','1'),
 ('54','VI','Virgin Islands','1'),
 ('55','VT','Vermont','1'),
 ('56','WA','Washington','1'),
 ('57','WI','Wisconsin','1'),
 ('58','WV','West Virginia','1'),
 ('59','WY','Wyoming','1'),
 ('60','AB','Alberta','40'),
 ('61','BC','British Columbia','40'),
 ('62','MB','Manitoba','40'),
 ('63','NB','New Brunswick','40'),
 ('64','NF','Newfoundland','40'),
 ('65','NL','Newfoundland and Labrador','40'),
 ('66','NS','Nova Scotia','40'),
 ('67','NT','Northwest Territories','40'),
 ('68','NU','Nunavut','40'),
 ('69','ON','Ontario','40'),
 ('70','PE','Prince Edward Island','40'),
 ('71','QC','Quebec','40'),
 ('72','SK','Saskatchewan','40'),
 ('73','YT','Yukon Territory','40');


insert into `ctx_data_types` values
 ('1','Affiliation','Faculty'),
 ('2','Department','Department'),
 ('3','Affiliation','Guest'),
 ('4','Status','Active'),
 ('5','Status','InActive'),
 ('6','Phone','Cell'),
 ('7','Phone','Home'),
 ('8','Phone','Campus'),
 ('9','Address','Home'),
 ('10','Address','Campus'),
 ('11','Email','Home'),
 ('12','Email','Campus'),
 ('13','Sponsor','Person'),
 ('14','NAME','FORMAL'),
 ('15','Affiliation','Staff'),
 ('16','Affiliation','Student');


insert into `prd_identifier_types` (`identifier_t`,`name`,
  `deleted`,
  `description`,
  `format`,
  `modifiable`,
  `private`,
  `notifiable`)
  values
  ('1','SSN',b'00000000','ID Description','',b'00000000',b'00000000',b'00000000'),
 ('2','RUID',b'00000000','ID Description','',b'00000000',b'00000000',b'00000000'),
 ('3','RCPID',b'00000000','ID Description','',b'00000000',b'00000000',b'00000000'),
 ('4','IID',b'00000000','ID Description','',b'00000000',b'00000000',b'00000000'),
 ('5','NETID',b'00000000','ID Description','',b'00000000',b'00000000',b'00000000');


insert into `prd_campuses` values
 ('1','01', 'Main Campus'),
 ('2','02', 'Satellite Campus');

insert into `drd_organizational_units` values
('1','UNSPEC','',1,null,'2'),
('2','ITS','IT Services',1,null,'2'),
('3','ICAT','Institutional Collaborative and Academic Technologies','2','1','2'),
('4','ITI','IT Infrastructure','2',1,'2'),
('5','PHIL','Philosophy','2',null,'2');

insert into `prd_system_of_record` values ('1','or-webapp');

insert into `prd_roles` values
('1','STAFF','Staff','15',1,1),
('2','FAC','Faculty','1',1,1),
('3','STU','Student','16',1,1),
('4','GRAD','Grad Student','16',1,1);
